quarkus.datasource.db-kind=mariadb
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:mariadb://localhost:3306/keykloack

quarkus.oidc.auth-server-url=http://127.0.0.1:8081/realms/dive-dev